language: node_js
node_js:
  - "11"
before_script:
  - npm install
script: npm run build
deploy:
  local-dir: dist/collegues-front
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
notifications:
  email: false